//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int p_id { get; set; }
        public Nullable<double> p_amount { get; set; }
        public Nullable<int> c_id { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
